image: docker:git
services:
- "docker:dind"

before_script:
- "docker login -u "$REGISTRY_USER" -p "$REGISTRY_TOKEN" $REGISTRY_HOST"
- "mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2"
- "curl -SL https://github.com/grammarly/rocker/releases/download/1.3.0/rocker_linux_amd64.tar.gz | tar -xzC /usr/bin"

variables:
  TAG: latest
  DOCKER_DRIVER: overlay

build:
  stage: build
  script:
  - "rocker build -f haskell-build-ghcjs-runner/Rockerfile haskell-build-ghcjs-runner"
  - "docker tag haskell-build-runner:latest $REPO:$TAG"
  - "docker push $REPO:$TAG"
