image: docker:git
services:
- "docker:dind"

before_script:
- "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com"

variables:
  REPO: registry.gitlab.com/quyse/haskell-hacks
  DOCKER_DRIVER: overlay

build:
  stage: build
  script:
    - "docker build -t $REPO -f haskell-build-ghcjs-runner/Dockerfile_arch haskell-build-ghcjs-runner"
    - "docker push $REPO:latest"
